if (!require("pacman")) install.packages("pacman", repos="https://cran.r-project.org/")
if (!require("BiocManager")) install.packages("BiocManager", repos="https://cran.r-project.org/")

message(" | ", Sys.time(), " Verifying conda installation for R package dependencies...")

pacman::p_load(tidyverse, later, parallel, optparse, purrr, visNetwork, ggpubr, grid, gridExtra, vegan, plotly, ggrepel, viridis, igraph, Hmisc)
library(tidyverse)
library(later)
library(parallel)
library(optparse)
library(purrr)
library(visNetwork)
library(ggpubr)
library(grid)
library(gridExtra)
library(vegan)
library(plotly)
library(ggrepel)
library(viridis)
library(igraph)
library(Hmisc)
library(ggdendro)
#library(treeio)
#library(ggtree)

#message(" | ", Sys.time(), " Double checking other R package dependencies from bioconductor...")
#if (!require("treeio")) BiocManager::install("treeio")
#if (!require("ggtree")) BiocManager::install("ggtree")

message(" | ", Sys.time(), " Installing bngal R package from GitHub...")
pacman::p_install_gh("mselensky/bngal")
